name = "cloudf"
compatibility_date = "2024-03-28"
compatibility_flags = ["nodejs_compat"]

# Point vers le fichier serveur compilé
main = "dist/server/index.js"

# Configuration des assets statiques
[site]
bucket = "dist/client"

# Configuration de build
[build]
command = "npm run build"

# Variables d'environnement globales
[vars]
PUBLIC_STORE_DOMAIN = "mock.shop"
PUBLIC_STOREFRONT_API_TOKEN = "3b580e70970c4528da70c98e097c2fa0"
SESSION_SECRET = "2939230293hdhdas"

# Pour différencier les environnements
[env.production.vars]
PUBLIC_STORE_DOMAIN = "mock.shop"
PUBLIC_STOREFRONT_API_TOKEN = "3b580e70970c4528da70c98e097c2fa0"
SESSION_SECRET = "2939230293hdhdas"

[env.development.vars]
PUBLIC_STORE_DOMAIN = "mock.shop"
PUBLIC_STOREFRONT_API_TOKEN = "3b580e70970c4528da70c98e097c2fa0"
SESSION_SECRET = "2939230293hdhdas" 